version: 2.1

jobs:
  initial:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: echo 'yep'
      - run:
          name: push comment to github pr
          command: |
            sudo apt-get install jq

            pr_response=$(curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH&state=open" \
            -u $GH_USER:$GH_TOKEN)

            if [ $(echo $pr_response | jq length) -eq 0 ]; then
              echo "No PR found to update"
            else
              pr_comment_url=$(echo $pr_response | jq -r ".[]._links.comments.href")
            fi

            curl --location --request POST "$pr_comment_url" \
            -u $GH_USER:$GH_TOKEN \
            --header 'Content-Type: application/json' \
            --data-raw '{
            "body": "This would be the data to add"
            }'

workflows:
  version: 2
  test_flow:
    jobs:
      - initial
