version: 2.1

jobs:
  initial:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: echo 'yep'
      - run:
          name: push comment to github pr
          command: |
            echo $GH_TOKEN
            echo $GH_USER

workflows:
  version: 2
  test_flow:
    jobs:
      - initial
